bashLoad --> import

diff --git a/bash_programming b/bash_programming
--- a/bash_programming
+++ b/bash_programming
@@ -8,15 +8,15 @@ declare -x BASH_LIB=$HOME/lib/shellLib
 #
 # Function to source shell library functions
 #
-bashLoad ()
+import ()
 {
-    if ! source $BASH_LIB/$1; then
-        if [ ! -d "$BASH_LIB" ]; then
-            echo "[ERROR] BASH_LIB $BASH_LIB does not exist" && exit 1
+    if ! source "${BASH_LIB}/$1"; then
+        if [ ! -d "${BASH_LIB}" ]; then
+            echo "[ERROR] BASH_LIB ${BASH_LIB} does not exist" && exit 1
         fi
     fi
 }
-export -f bashLoad
+export -f import
 
 # -----------------------------------------------------------
 
